package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Punto único de acceso a la base de datos (patrón Singleton), tal como pide
 * la evaluación. Usa H2 en modo archivo: no requiere instalar un motor
 * aparte, y los datos quedan guardados en el home del usuario entre
 * ejecuciones.
 */
public final class ConexionBD {

    private static final String URL =
            System.getProperty("biblioteca.db.url", "jdbc:h2:~/biblioteca_untec;MODE=MySQL");
    private static final String USUARIO = "sa";
    private static final String CLAVE = "";

    private static final ConexionBD INSTANCIA = new ConexionBD();

    private Connection conexion;

    private ConexionBD() {
        try {
            // H2 registra su driver automáticamente, pero lo cargamos de
            // forma explícita para que un problema de dependencias falle
            // con un mensaje claro en vez de un "No suitable driver".
            Class.forName("org.h2.Driver");
            abrirConexion();
            crearTablasSiNoExisten();
        } catch (Exception e) {
            throw new IllegalStateException("No fue posible inicializar la base de datos.", e);
        }
    }

    /**
     * Devuelve la única instancia de esta clase (patrón Singleton).
     *
     * @return la instancia compartida de {@code ConexionBD}
     */
    public static ConexionBD getInstancia() {
        return INSTANCIA;
    }

    /**
     * Entrega una conexión JDBC lista para usar, abriendo una nueva
     * si la anterior ya se cerró.
     *
     * @return una conexión activa a la base de datos
     * @throws SQLException si no es posible abrir la conexión
     */
    public synchronized Connection getConexion() throws SQLException {
        if (conexion == null || conexion.isClosed()) {
            abrirConexion();
        }
        return conexion;
    }

    private void abrirConexion() throws SQLException {
        conexion = DriverManager.getConnection(URL, USUARIO, CLAVE);
    }

    private void crearTablasSiNoExisten() throws SQLException {
        try (Statement st = conexion.createStatement()) {

            st.execute("""
                    CREATE TABLE IF NOT EXISTS usuario (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR(120) NOT NULL,
                        correo VARCHAR(160) NOT NULL UNIQUE,
                        contrasena VARCHAR(120) NOT NULL
                    )
                    """);

            st.execute("""
                    CREATE TABLE IF NOT EXISTS libro (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        isbn VARCHAR(30) NOT NULL UNIQUE,
                        titulo VARCHAR(180) NOT NULL,
                        autor VARCHAR(160) NOT NULL,
                        ejemplares_totales INT NOT NULL,
                        ejemplares_disponibles INT NOT NULL,
                        activo BOOLEAN NOT NULL DEFAULT TRUE
                    )
                    """);

            st.execute("""
                    CREATE TABLE IF NOT EXISTS prestamo (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        usuario_id BIGINT NOT NULL,
                        libro_id BIGINT NOT NULL,
                        fecha_prestamo DATE NOT NULL,
                        fecha_devolucion DATE NULL,
                        devuelto BOOLEAN NOT NULL DEFAULT FALSE,
                        FOREIGN KEY (usuario_id) REFERENCES usuario(id),
                        FOREIGN KEY (libro_id) REFERENCES libro(id)
                    )
                    """);

            // Usuario de prueba para poder iniciar sesión desde el primer momento.
            st.execute("""
                    MERGE INTO usuario (id, nombre, correo, contrasena)
                    KEY (id)
                    VALUES (1, 'Estudiante Demo', 'alumno@untec.cl', '1234')
                    """);

            st.execute("""
                    MERGE INTO libro (id, isbn, titulo, autor, ejemplares_totales, ejemplares_disponibles, activo)
                    KEY (id)
                    VALUES
                        (1, '9789566180166', 'En las montañas de la locura', 'H.P. Lovecraft', 1, 1, TRUE),
                        (2, '9780765317384', 'Los juegos de Ender', 'Orson Scott Card', 2, 2, TRUE),
                        (3, '978-956-12-2377-6', 'La Porota', 'Marcela Paz', 1, 1, TRUE)
                    """);
        }
    }
}